# Generated by Django 4.0.6 on 2022-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_delete_userregmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('designation', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
